excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  excluded:
    - id
type_name:
  excluded:
    - iCarUITests
    - iCarTests
line_length: 200
custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
file_name:
  excluded:
    - main.swift
disabled_rules: # rule identifiers to exclude from running
#  - line_length
  - large_tuple
  - identifier_name
  - control_statement