# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iCar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iCar

  target 'iCarTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'iCarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'SwiftLint', :inhibit_warnings => true
    pod 'ARSLineProgress', '~> 2.0' , :inhibit_warnings => true
    pod 'Kingfisher', '~> 4.0' , :inhibit_warnings => true
end
